id: ABD6D4D8A
base_file: fAD0D.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:50:54.559599
  last_modified_at: 2022-05-31 06:50:54.559604
