id: ABD6D4D8A
base_file: fE603.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:50:54.564914
  last_modified_at: 2022-05-31 06:50:54.564919
