id: ABD6D4D8A
base_file: f02B5.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:50:54.535161
  last_modified_at: 2022-05-31 06:50:54.535171
