id: ABD6D4D8A
base_file: f1FB5.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:50:54.540109
  last_modified_at: 2022-05-31 06:50:54.540112
