id: ABD6D4D8A
base_file: f32B3.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:50:54.547659
  last_modified_at: 2022-05-31 06:50:54.547666
