id: ABD6D4D8A
base_file: f22E6.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:50:54.541999
  last_modified_at: 2022-05-31 06:50:54.542002
