id: ABD6D4D8A
base_file: f804C.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:50:54.553100
  last_modified_at: 2022-05-31 06:50:54.553102
