id: ABD6D4D8A
base_file: fC245.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:50:54.562790
  last_modified_at: 2022-05-31 06:50:54.562795
