id: ABD6D4D8A
base_file: f9E1B.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:50:54.555666
  last_modified_at: 2022-05-31 06:50:54.555669
